# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: sudo apt-get install vim
  displayName: 'Install vim'

- script: python3 install_gadget.py
  displayName: 'Install gadgets'

- script: ./run_tests
  displayName: 'Run the tests'