# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu-16.04'

container: 'ubuntu:18.04'

steps:
- script: printenv
  displayName: 'Print environment'

- script: whoami
  displayName: 'Print user'

- script: apt-get install python3-dev vim
  displayName: 'Install vim'

- script: python3 install_gadget.py
  displayName: 'Install gadgets'

- script: ./run_tests
  displayName: 'Run the tests'
