name: Bug Report
description: File a bug report
title: ''
labels: ''
assignees: ''
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report. It's important
        to complete it in full, as this maximises the likelihood that it can be
        reproduced and ultimately fixed.

        Please note, if your issue is NOT a bug report, then this is not the
        form to use. If your issue ammounts to a feature request, or a request
        for help, then it may be closed without comment.

        Please make sure you have read
        [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md#diagnostics)
        before raising an issue. If it becomes clear that you have not, the
        issue will be closed.
